Feature/standardized font size and layout fixes
Universal-Debloater-Alliance/universal-android-debloater pull request #118
Opened 2023-12-24 21:57 UTC by Frigyes06

2023-12-24 22:03 UTC, adhirajsinghchauhan requested changes

2023-12-24 22:03 UTC, adhirajsinghchauhan commented on src/gui/views/list.rs
> +                        .size(16),
Would be better to set `default_text_size: 16.0` in mod.rs, and remove all `size(16)`s.

2023-12-24 22:03 UTC, adhirajsinghchauhan commented on src/gui/views/list.rs
>                          .width(17)
nit: I'd suggest increasing icon widths to make the button containers appear more square; looks better.

22 should do it (also in navigation_menu.rs).

2023-12-24 22:13 UTC, adhirajsinghchauhan approved these changes

2023-12-24 22:15 UTC, Frigyes06 commented
![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/assets/72750891/974ade1d-9009-48a3-be4c-41a25a14cdc6)
These texts get a bit cut off

2023-12-24 22:17 UTC, merged

2024-04-17 02:57 UTC, shapeshifterincontext commented
Can we go back to the font and size used in this. V1.0.3 is not 'bad eyesight' friendly. The letters in each word are squashed together.

2024-09-05 06:44 UTC, Rudxain commented
> Can we go back to the font and size used in this.

I agree, the text is too small

2024-09-05 06:51 UTC, adhirajsinghchauhan commented
Could you please post screenshots? We didn't change text sizes again after this PR.

2024-09-05 07:29 UTC, Rudxain commented
`cargo run` on `main`:
![Screenshot  2024-09-05 03-14-54](https://github.com/user-attachments/assets/f5867e3c-1f45-4141-9de1-cdbc428c66dd)

- Linux 6.10
- Debian 13 "Trixie"
- GNOME 46
- Wayland 1.23 (+ Mutter)
- Intel HD Graphics 4000
- Display resolution = 1366×768 px
- GNOME display scale = 1x (hidden from GUI, because display is not "hi-DPI")
- Tweaks "Font" size scale factor = 1.5

2024-09-05 07:33 UTC, AnonymousWP commented
For me it doesn't look small, neither does the text on your screenshot.

2024-09-05 08:04 UTC, Rudxain commented
The review modal text isn't small, but it is relative to this
![img](https://private-user-images.githubusercontent.com/72750891/292690944-974ade1d-9009-48a3-be4c-41a25a14cdc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjI0NzAsIm5iZiI6MTcyNTUyMjE3MCwicGF0aCI6Ii83Mjc1MDg5MS8yOTI2OTA5NDQtOTc0YWRlMWQtOTAwOS00OGEzLWJlNGMtNDFhMjVhMTRjZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA3NDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZDIwYTZkYjMwMzFiZTk1YmJiYjAxNTUwMTE5M2Q0ZTIzYTA5Y2Q3M2EwYjFkMzkwODY1NzRjNDlkZjk5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oSm5sYfipTo5_BEKdPknuoQUjI5u4fgbauXvd1Prn9o)

Although the pack list seems even smaller to me

2024-09-05 08:06 UTC, AnonymousWP commented
> The review modal text isn't small, but it is relative to this ![img](https://private-user-images.githubusercontent.com/72750891/292690944-974ade1d-9009-48a3-be4c-41a25a14cdc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjI0NzAsIm5iZiI6MTcyNTUyMjE3MCwicGF0aCI6Ii83Mjc1MDg5MS8yOTI2OTA5NDQtOTc0YWRlMWQtOTAwOS00OGEzLWJlNGMtNDFhMjVhMTRjZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA3NDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZDIwYTZkYjMwMzFiZTk1YmJiYjAxNTUwMTE5M2Q0ZTIzYTA5Y2Q3M2EwYjFkMzkwODY1NzRjNDlkZjk5YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oSm5sYfipTo5_BEKdPknuoQUjI5u4fgbauXvd1Prn9o)
> 
> Although the main pack list (the one behind the modal) seems even smaller to me

Your screenshot returns a 404. It's a private user URL.

2024-09-06 01:27 UTC, Rudxain commented
> 404

That's odd 👀😕. It's the same screenshot [from here](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/118#issuecomment-1868602553). Both load from my POV

2024-09-06 04:01 UTC, adhirajsinghchauhan commented
> > 404
> 
> That's odd 👀😕. It's the same screenshot [from here](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/118#issuecomment-1868602553). Both load from my POV

Notice the `jwt` parameter in that URL, though. It would differ per session, so what works for you won't work for others. Not sure if this token could be used to gain access to your account, but I'd contact GitHub anyway, to scrub your comment.

2024-09-06 05:44 UTC, Rudxain commented
> `jwt`

[It seems to have an expiration date](https://github.com/orgs/community/discussions/109034#discussioncomment-9545999)

So there's not much to worry about. I'll replace the screenshot anyways

2025-01-04 04:10 UTC, Rudxain commented
Now that I'm using a hi-DPI (1080p) display, I've set scale=2 in the GNOME Settings. The widgets are bigger!