feat: rename project name to Universal Android Debloater (UAD-NG)
Universal-Debloater-Alliance/universal-android-debloater pull request #124
Opened 2023-12-26 13:27 UTC by AnonymousWP

As for why, including context, please see this discussion/poll: https://github.com/Universal-Debloater-Alliance/universal-android-debloater/discussions/54.

For the developers: see from [here](https://discord.com/channels/1168607797081022514/1171387180409692160/1188826128803188826) onwards.

Fixes #120.

2023-12-26 21:09 UTC, Frigyes06 commented
I'd use UADng or UAD-ng instead of UAD-NG

2023-12-28 22:36 UTC, adhirajsinghchauhan submitted a review, later dismissed

2023-12-28 22:59 UTC, Frigyes06 requested changes

2023-12-28 22:59 UTC, Frigyes06 commented on src/gui/widgets/navigation_menu.rs
> +                "New UAD-ND version available {} -> {}",
-ng

2023-12-28 22:59 UTC, Frigyes06 commented on Cargo.lock
> +name = "uad_ng"
uad-ng
match cargo.toml
Lockfile should not be manually modified, but rather regenerated with cargo

2024-01-03 03:51 UTC, Frigyes06 approved these changes

2024-01-03 03:52 UTC, merged