Aded discord invite to readme
Universal-Debloater-Alliance/universal-android-debloater pull request #131
Opened 2023-12-27 23:06 UTC by Frigyes06

2023-12-27 23:31 UTC, adhirajsinghchauhan requested changes

2023-12-27 23:31 UTC, adhirajsinghchauhan commented on README.md
> +**For the most up-to-date information and real-time communication, please join our discord!**
I don't think it's our intention to provide "up-to-date information" on Discord. We can (and should) do that here on GitHub itself.

Per https://github.com/Universal-Debloater-Alliance/universal-android-debloater/issues/126#issuecomment-1870689586, imo a rephrase is necessary to make it obvious that people can join _only if they want_, not because they may miss out on something or other. We're not here to peer pressure or FOMO them into joining.

I'm open to other opinions in case I'm missing a benefit of having a Discord server.

2023-12-28 00:01 UTC, adhirajsinghchauhan requested changes

2023-12-28 00:01 UTC, adhirajsinghchauhan commented on README.md
> +**For real-time communication please consider joining our Discord server!**
Hmm "please consider joining" is more coercive than polite. Dropping the please should be good I think, but we can wait for others before changing it yet again.

2023-12-28 20:40 UTC, AnonymousWP commented on README.md
> +**For real-time communication please consider joining our Discord server!**
I agree.

2023-12-28 20:41 UTC, AnonymousWP requested changes

2023-12-28 20:41 UTC, AnonymousWP commented on README.md
> +**For real-time communication please consider joining our Discord server!**
```suggestion
**For real-time communication, consider joining our Discord server!**
```

2023-12-28 23:03 UTC, AnonymousWP approved these changes

2024-01-03 03:51 UTC, adhirajsinghchauhan approved these changes

2024-01-03 09:43 UTC, merged