feat(ui): move select and deselect all actions to more intuitive checkbox
Universal-Debloater-Alliance/universal-android-debloater pull request #146
Opened 2024-01-01 12:50 UTC by lavafroth

### Changes
- Removes "Select all" and "Unselect All" button from the bottom row
- Adds a checkbox to the top row in line with the package checkbox entries for a more intuitive "select all" and "deselect all" experience

2024-01-01 19:22 UTC, Frigyes06 commented
Woag another UI contributor

2024-01-01 20:47 UTC, adhirajsinghchauhan commented
While I like the idea, my main issue with it is that it's not perfectly aligned with other checkbox. It would need some manual tweaking.

Another minor issue is accessibility-related: the separate buttons at least conveyed their actions more obviously. Not everyone is familiar with the concept of a global checkbox. Adding an overlay on hover that conveys its meaning — based on state — would be better.

2024-01-02 01:40 UTC, lavafroth commented
@adhirajsinghchauhan sure, I'll implement that.

2024-01-02 02:57 UTC, lavafroth commented
Alright, should be good now. I also updated the screenshots.

2024-01-02 04:07 UTC, adhirajsinghchauhan requested changes

2024-01-02 04:07 UTC, adhirajsinghchauhan commented on src/gui/views/list.rs
> +                    checkbox("Select all", self.all_selected, Message::ToggleAllSelected)
Tooltip would be better than a label, as it won't take up valuable space in the row. Also, text displayed should change based on `all_selected`.

I'll implement these changes myself.

2024-01-02 04:11 UTC, adhirajsinghchauhan commented on src/gui/views/list.rs
> +                    checkbox("Select all", self.all_selected, Message::ToggleAllSelected)
Done (shown only on hover):

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/assets/14949823/9300495d-f79c-4370-9a6a-eb1a61ae109c)

![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/assets/14949823/b49dba40-e80d-4136-b068-6849b9c30cf0)

2024-01-02 04:11 UTC, adhirajsinghchauhan approved these changes

2024-01-02 04:13 UTC, merged

2024-01-02 05:03 UTC, lavafroth commented on src/gui/views/list.rs
> +                    checkbox("Select all", self.all_selected, Message::ToggleAllSelected)
Thanks 😃