huawei packages + changes descriptions
Universal-Debloater-Alliance/universal-android-debloater pull request #68
Opened 2023-12-06 15:59 UTC by Blitz517

better ideas

2023-12-06 23:29 UTC, AnonymousWP requested changes
Thanks for this big PR, but a few things to keep in mind:

- In the future, please split PRs in adding packages and changing descriptions. It's a lot to review.
- Please keep an eye on grammar and spelling. It costs a lot of time to fix.

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Guard Provider security app\nThe app includes 3 different antivirus brands built in that the user can choose (Avast, AVL and Tencent). \nThis app notably perform a virus scan of a
```suggestion
    "description": "Guard Provider security app\nThe app includes 3 different antivirus brands built in that the user can choose (Avast, AVL and Tencent). \nThis app notably perform a virus scan of any apps you want to install. \nA serious vulnerability was found in 2019\nWorth reading : https://research.checkpoint.com/2019/vulnerability-in-xiaomi-pre-installed-security-app/\nYou may want to remove this app from a privacy stance.\nhttps://beta.pithus.org/report/797a7e405bc8e767deebbbcab3e06a19b05156de44292c918b582dff3078d7b8\nIMPORTANT NOTE: Removing this package will very likely break any app installation/update.\nBefore removing, disable security things in MIUI security app",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "HwCameraKit\nIn code founded that its for testing camera things.",
```suggestion
    "description": "HwCameraKit\nIn the code it was found that it's for testing camera functions.",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Not needed overlay, only has code to set googlequicksearchbox as default assistant",
```suggestion
    "description": "Not needed overlay, only has code to set `googlequicksearchbox` as default assistant",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Air link service, its problably needed for Wireless Projection.\nNo activities, only more debugging stuff, location things, logs",
```suggestion
    "description": "Air link service, it's probably needed for Wireless Projection.\nNo activities, only more debugging stuff, location things, logs",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Wireless Projection\nMiracast, Require Huawei Mobile Services, also its so bloated, also found unused frameworks HUAWEI GameCenter",
```suggestion
    "description": "Wireless Projection\nMiracast, Requires Huawei Mobile Services, also it's so bloated, also found unused frameworks HUAWEI GameCenter",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Audio Accessory Manager\nA lot stuff: huawei health, huawei music, earphones.\nProblably useful when you got HUAWEI FreeBuds.",
```suggestion
    "description": "Audio Accessory Manager\nA lot stuff: Huawei health, Huawei music, earphones.\nProbably only useful when you got Huawei FreeBuds.",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "HwCoAuthService\nFounded Applock, lockscreen password, face recognition things, fingerprint, not sure if its worth removing it",
```suggestion
    "description": "HwCoAuthService\nApplock, lockscreen password, face recognition things, fingerprint, not sure if it's worth removing it",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "ContentSensor\nIts app only for call logs",
```suggestion
    "description": "ContentSensor\nIt's an app only for call logs",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```
Call logs can be seen as something essential.

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "DEF\nUnused? message things:Allows the app public keys on connected devices, getting status, access information",
```suggestion
    "description": "DEF\nUnused? message things: allows the app public keys on connected devices, getting status, access information",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "TrustedDeviceAuth\nI guess its for authentication keys",
```suggestion
    "description": "TrustedDeviceAuth\nI guess it's for authentication keys",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "id": "com.huawei.devicegroupmanage",
```suggestion
    "id": "com.huawei.devicegroupmanager",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "(Unused?)HwGroupManager\nIts app without activities, only device info things",
```suggestion
    "description": "(Unused?)HwGroupManager\nIt's an app without activities, only device info things",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Needed for huawei account. I found only things: installing service?, Linked devices, Multi-Device management, connection code, metrics",
```suggestion
    "description": "Needed for Huawei account. I found only things: installing service? Linked devices, Multi-Device management, connection code, metrics",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
If it's for a Huawei account, do you think an account is required to use those features in the description?

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "HwDistributedKeyManager\nHas random frameworks, problably needed for huawei account, authentication",
```suggestion
    "description": "HwDistributedKeyManager\nHas random frameworks, probably needed for Huawei account, authentication",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Same as above.

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Multi-Device management\nThis service allows you to virtually expand your devices capabilities\nby connecting to other devices and using them as an extension of this device.",
```suggestion
    "description": "Multi-Device management\nThis service allows you to virtually expand your devices capabilities\nBy connecting to other devices and using them as an extension of this device.",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "needed for messages bluethooth, wifi, hotspot, Terms of Agreement, Authentication",
```suggestion
    "description": "Needed for messages Bluetooth, wifi, hotspot, Terms of Agreement, Authentication",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "foundation\nThird-party service names, its a trackers.\nAlso founded com.huawei.cloud.hianalytics.aspg\nand connects to metrics hicloud site.",
```suggestion
    "description": "foundation\nThird-party service names, it's a tracker.\nAlso found `com.huawei.cloud.hianalytics.aspg`\nand connects to metrics hicloud site.",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "AI Life Service\nUsed for smart devices and to run smart scenes.\nIts more useful in china.",
```suggestion
    "description": "AI Life Service\nUsed for smart devices and to run smart scenes.\nIt's more useful in China.",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Hw5GKitAgentService\nOnly debugging code founded that apk id is invalid, disable parameter error, other error things.",
```suggestion
    "description": "Hw5GKitAgentService\nOnly debugging code found that APK id is invalid, disable parameter error, other error things.",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "HwDiagnosis\nNo activities, only code about diagnosis and logs\nalso device info and send to huawei servers.",
```suggestion
    "description": "HwDiagnosis\nNo activities, only code about diagnosis and logs\nAlso device info and is send to Huawei servers.",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "hivideoplayengine\nHwVideoKitImpl, Not sure if its needed for video player",
```suggestion
    "description": "hivideoplayengine\nHwVideoKitImpl, Not sure if it's needed for video player",
```

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "only random names agc_... and fa panel name",
I don't understand this description.

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Futótárs\nApp for training, so bloated and from T-Mobile",
Please use an English translation for Hungarian.

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Mobilvásárlás\nApp for watch tv on phone, so bloated (a lot spying) and from T-Mobile",
Same as above.

2023-12-06 23:29 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Műsorújság\nAnother app to tv things, so bloated and from T-Mobile, not needed",
Same as above.

2023-12-07 19:16 UTC, AnonymousWP requested changes
- No more new commits; push new packages/descriptions etc. in a new, preferably separate PRs
- Check all descriptions where you use 'probably': it's not bad, but as we're unsure about the safety of a removal, we can't safely say using a Recommended removal is a smart idea when we haven't tested it as you use 'probably'.

2023-12-07 19:16 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Camera consent AI\nCamera consent AI? artificial intelligence models? Probably addional features to camera app",
```suggestion
    "description": "Camera consent AI\nCamera consent AI? Artificial Intelligence models? Probably additonal features to camera app",
```

2023-12-07 19:16 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Game Notes\nGame Notes? Probably its optional thing.",
```suggestion
    "description": "Game Notes\nGame Notes? Probably an optional thing.",
```

2023-12-09 11:28 UTC, RevisionOSS commented on resources/assets/uad_lists.json
> +    "description": "Not needed overlay, only has code to set googlequicksearchbox as default assistant",
Added App name to make it clarity.

```suggestion
    "description": "Not needed overlay, only has code to set `googlequicksearchbox`(Google App) as default assistant",
```

2023-12-10 13:52 UTC, kyoforkshomebrews commented
Seems dsdscardmanager is missing from here 
`},
    {
    "id": "com.huawei.android.dsdscardmanager",
    "list": "Oem",
    "description": "SIM management",
    "dependencies": [],
    "neededBy": [],
    "labels": [],
    "removal": "Expert"
  },`

2023-12-12 13:43 UTC, kyoforkshomebrews commented
I wouldn't put com.huawei.entitlement and com.huawei.permissioncontroller.overlay in unsafe. I have disabled them and I have yet to notice anything missing or not working.

I would put com.huawei.entitlement in expert, on some phones it might be ok to disable it and on others you lose a bunch of features, but as long as it doesn't cause a bootloop it should be fine.
Probably same with permissioncontroller except on my phone it doesn't have code so it's entirely unneeded.

2023-12-12 13:53 UTC, kyoforkshomebrews commented
### com.android.systemui.overlay
**List**: `Oem`
**Removal**: `Unsafe`
> System UI Overlay. DO NOT remove this.

2023-12-12 15:41 UTC, AnonymousWP commented
@kyoforkshomebrews Please add suggestions as a review. Addition of packages should be done in a new issue/PR.

2023-12-15 14:14 UTC, kyoforkshomebrews commented on resources/assets/uad_lists.json
> +    "removal": "Unsafe"
I wouldn't put com.huawei.entitlement in unsafe. I have disabled it and I have yet to notice anything missing or not working. I'd put it in expert, on some phones it might be ok to disable it and on others you lose a bunch of features, but as long as it doesn't cause a bootloop it should be fine.

2023-12-15 14:16 UTC, kyoforkshomebrews commented on resources/assets/uad_lists.json
> +    "removal": "Unsafe"
I wouldn't put com.huawei.permissioncontroller.overlay in unsafe. I have disabled it and I have yet to notice anything missing or not working. On my phone it has no code according to App Manager.

2023-12-16 12:49 UTC, AnonymousWP commented
Closing this PR as per request of @Blitz517. @kyoforkshomebrews Thanks for all the suggestions. Could you add your review with suggestions to the new PR? https://github.com/Universal-Debloater-Alliance/universal-android-debloater/pull/86/files#submit-review

2023-12-16 12:49 UTC, closed without merging