pkg: Add more POCO apps from MIUI 14 and Change some removal status
Universal-Debloater-Alliance/universal-android-debloater pull request #73
Opened 2023-12-07 15:24 UTC by RevisionOSS

2023-12-07 16:09 UTC, AnonymousWP requested changes
Thanks for your PR. Please pay attention to spelling and grammar next time if possible.

2023-12-07 16:09 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Poco Community\nIts only forum and community app for POCO phones.",
```suggestion
    "description": "Poco Community\nIt's only a forum and community app for POCO phones.",
```

2023-12-07 16:09 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "POCO Store\nIts a official POCO online store.\nhttps://play.google.com/store/apps/details?id=com.mi.global.pocostore",
```suggestion
    "description": "POCO Store\nIt's an official POCO online store.\nhttps://play.google.com/store/apps/details?id=com.mi.global.pocostore",
```

2023-12-07 16:09 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Xiaomi Gallery Editor\nExtension for MIUI Gallery that use for edit photos and videos.",
```suggestion
    "description": "Xiaomi Gallery Editor\nExtension for MIUI Gallery that's used to edit photos and videos.",
```

2023-12-08 00:47 UTC, RevisionOSS commented on resources/assets/uad_lists.json
> +    "description": "Poco Community\nIts only forum and community app for POCO phones.",
Thank you for your advice, next time I will do better.

2023-12-08 12:48 UTC, ProtonOSS approved these changes
LGTM

2023-12-08 14:03 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Application Extension Service\nIt's password manager in settings, requires Mi Account to Autofill and it syncs to your account.",
```suggestion
    "description": "Application Extension Service\nIt's a password manager in settings, requires Mi Account to Autofill and it syncs to your account.",
```

2023-12-08 14:05 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Package installer\nHardcoded in Xiaomi china Rom.\nCause BOOTLOOP.\nIt's weird when after a month this app is gone from my phone for no reason and Android enabled stock package in
```suggestion
    "description": "Package installer\nHardcoded in Xiaomi China ROM.\nCauses BOOTLOOP when removed.\nIt's weird when after a month this app is gone from my phone for no reason and Android enabled stock package installer.",
```

2023-12-08 14:05 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Package installer\nHardcoded in Xiaomi china Rom.\nCause BOOTLOOP.\nIt's weird when after a month this app is gone from my phone for no reason and Android enabled stock package in
You think `Unsafe` is still fitting? Does it cause a bootloop on non-Chinese phones too? If not, maybe we should make it `Recommended` instead then, don't you think so?

2023-12-08 14:06 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Mi Mover (https://play.google.com/store/apps/details?id=com.miui.huanji)\nLets you transfer your contacts, messages, personal files, all the installed apps (but not their data) \n
```suggestion
    "description": "Mi Mover (https://play.google.com/store/apps/details?id=com.miui.huanji)\nLets you transfer your contacts, messages, personal files, all the installed apps (but not its data). Also all the settings (app + system) from an Android phone to a Xiaomi phone.\nThe two phones will establish a direct Wi-Fi connection.\n",
```

2023-12-08 14:06 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "textaction\nIt's probably used for FrequentPhrase(com.miui.phrase) but also Frequent Phrases is an unknown app so its safe to remove.",
```suggestion
    "description": "textaction\nIt's probably used for FrequentPhrase(`com.miui.phrase`) but also Frequent Phrases is an unknown app so its safe to remove.",
```

2023-12-08 14:07 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "app that doesn't do anything, no code. Safe to remove.\n You will need remove it 2 times.",
```suggestion
    "description": "App that doesn't do anything, no code. Safe to remove.\n You will need to remove it twice.",
```

2023-12-08 14:07 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "app that doesn't do anything, no code. Safe to remove.",
```suggestion
    "description": "App that doesn't do anything, no code. Safe to remove.",
```

2023-12-08 14:09 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Dependency for MIUI Messaging (MIUI SMS app misleadingly called com.android.mms)\nYou can remove it if you don't use the default SMS app (and you should)\nRun in the background on
```suggestion
    "description": "Dependency for MIUI Messaging (MIUI SMS app misleadingly called `com.android.mms`)\nYou can remove it if you don't use the default SMS app (and you should). Run in the background once the phone is booted, has access to the internet and interact with Cloud Manager.",
```

Are you sure you mean "should" instead of "shouldn't"?

2023-12-08 22:20 UTC, RevisionOSS commented on resources/assets/uad_lists.json
> +    "description": "Application Extension Service\nIt's password manager in settings, requires Mi Account to Autofill and it syncs to your account.",
Thank you for your advice.

2023-12-08 22:36 UTC, RevisionOSS commented on resources/assets/uad_lists.json
> +    "description": "Dependency for MIUI Messaging (MIUI SMS app misleadingly called com.android.mms)\nYou can remove it if you don't use the default SMS app (and you should)\nRun in the background on
I Think so too.

2023-12-08 22:53 UTC, RevisionOSS commented on resources/assets/uad_lists.json
> +    "description": "Package installer\nHardcoded in Xiaomi china Rom.\nCause BOOTLOOP.\nIt's weird when after a month this app is gone from my phone for no reason and Android enabled stock package in
It doesn't BOOTLOOP on my MIUI Global.but It causes BOOTLOOP on Chinese ROM so change it to `Advanced`

2023-12-09 14:22 UTC, AnonymousWP approved these changes

2023-12-09 14:26 UTC, merged