0.6.2 release
Universal-Debloater-Alliance/universal-android-debloater pull request #75
Opened 2023-12-08 15:27 UTC by Frigyes06

2023-12-08 15:35 UTC, AnonymousWP requested changes

2023-12-08 15:35 UTC, AnonymousWP commented on CHANGELOG.md
> +### Apps
https://github.com/Universal-Debloater-Alliance/universal-android-debloater/pull/73 & https://github.com/Universal-Debloater-Alliance/universal-android-debloater/pull/68 are missing for when they will be merged.

2023-12-13 16:30 UTC, Frigyes06 commented on CHANGELOG.md
> +### Apps
Both of these PRs target main, not dev.

2023-12-13 16:36 UTC, AnonymousWP commented on CHANGELOG.md
> +### Apps
Then they should still be mentioned, no? Isn't that the entire purpose of keeping a changelog then? We need a more efficient way of doing this anyway.

2023-12-13 16:39 UTC, AnonymousWP approved these changes

2023-12-13 16:39 UTC, merged