Add some samsung apps
Universal-Debloater-Alliance/universal-android-debloater pull request #84
Opened 2023-12-15 08:50 UTC by prakharb5

2023-12-15 13:28 UTC, AnonymousWP requested changes

2023-12-15 13:28 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
Shouldn't this be Advanced instead? Because it can break important functionality.

2023-12-15 13:28 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Group Sharing (earlier Samsung Experience Service, before One UI 1.0). The the legacy version was similar to Samsung Core Services (citation needed).\nCan remove safely if you don
```suggestion
    "description": "Group Sharing (earlier Samsung Experience Service, before One UI 1.0). The legacy version was similar to Samsung Core Services (citation needed).\nCan remove safely if you don't use any group sharing features (shared albums in gallery, etc.).\nHandles your Samsung account and is needed to use some Samsung apps features.\nIt allows you to use multiple Samsung apps, such as Samsung Health, Samsung Pay, Galaxy Apps, Samsung Members, and SmartThings, \nwith your Samsung account credentials.\nhttps://techshift.net/what-is-samsung-group-sharing/",
```

2023-12-15 13:28 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "Video call effects\nKeep the focus on you during video calls by blurring the background or covering it with an image or color.\nUnfortunately, only supports a few apps (Google Mee
```suggestion
    "description": "Video call effects\nKeep the focus on you during video calls by blurring the background or covering it with an image or color.\nUnfortunately, only supports a few apps (Google Meet, WhatsApp, Zoom).",
```

2023-12-15 22:11 UTC, prakharb5 commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
You are right, it can break Quick Share. WIll make the change.

2023-12-16 12:50 UTC, AnonymousWP approved these changes

2023-12-16 12:56 UTC, merged