Added/Updated packages, descriptions
Universal-Debloater-Alliance/universal-android-debloater pull request #86
Opened 2023-12-16 00:22 UTC by Blitz517

added more packages and used from old pull requests add/changes packages, descriptions.

2023-12-16 16:47 UTC, AnonymousWP requested changes

2023-12-16 16:47 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "removal": "Recommended"
```suggestion
    "removal": "Advanced"
```
Some users may want to use this.

2023-12-16 16:47 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "list": "Oem",
```suggestion
    "list": "AOSP",
```

2023-12-16 16:47 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "MediaLibrary\nhas hwddmp components `com.huawei.hwddmp` debuging errors, remote device manager that depends on Huawei account",
```suggestion
    "description": "MediaLibrary\nhas hwddmp components `com.huawei.hwddmp` debugging errors, remote device manager that depends on Huawei account",
```

2023-12-16 16:47 UTC, AnonymousWP commented on resources/assets/uad_lists.json
> +    "description": "OneHopSvcHost\nTriggerservice, has only tracking things, hmskit that does not exist on the site of of Huawei.",
```suggestion
    "description": "OneHopSvcHost\nTriggerservice, has only tracking things, hmskit that does not exist on the site of Huawei.",
```

2023-12-16 18:49 UTC, Blitz517 commented on resources/assets/uad_lists.json
>      "id": "com.qualcomm.qtil.btdsda",
App size is too small

2023-12-16 22:14 UTC, AnonymousWP approved these changes

2023-12-16 22:14 UTC, merged

2025-01-25 23:58 UTC, Rudxain commented on resources/assets/uad_lists.json
> +    "id": "org.lineageos.profiles",
Why were these added? This should be documented by Lineage, not UAD

2025-01-25 23:59 UTC, Rudxain commented on resources/assets/uad_lists.json
> +  },
Why were these added? This should be documented by Lineage, not UAD

2025-01-26 00:29 UTC, Rudxain commented on resources/assets/uad_lists.json
> +  },
#812